#!/bin/bash

# nd: New Directory

# Changes directory, but creates it if it does not exist yet.

function nd()
{
    if [[ "${1:-}" ]]; then
        if [[ ! -e "$1" ]]; then
            mkdir --parent "$1" || return 1
        fi
        cd "$1" || return 1
    fi
}
#
